### ISSUE TITLE
skills friday🤩🤩 please add☝️🤓

### ISSUE THREAD

**Issue by MaximilianMcC** [MilkyBruv/AllegroTest#14]
I am writing to request that the project be updated on a _regular basis,_ specifically under the title **"Skills Friday"**. As an avid follower and user of the project, I believe that **consistent** updates will help to keep me and other users informed about the progress of the project.
# SKILLS FRIDAY
I understand that development can often be a **complex and time-consuming process,** but I believe that regular updates will provide valuable _insight_ into the project's progress and help us to better understand the work that is being done. It will also be beneficial for those who are interested in **contributing** to the project, as they can see the areas where the project may need assistance.
![wow](https://imgur.com/LXj9EM2.png)
I would also like to _suggest_ that these updates be posted on the project's website or social media pages, so that they are easily accessible to all users. Additionally, including screenshots or other **visual aids** would be helpful in illustrating the changes that have been made.
this is supported by issue #12 
Thank you for your time and consideration. I look forward to seeing the progress of the project through regular updates.

**Comment by alexoltl** [comment]
I completely agree with Max's idea of implementing a "Skills Friday" feature to Allegrotest. It would provide a great opportunity for employees to develop their skills and further their professional growth. With "Skills Friday," employees could choose from a variety of courses and workshops that are relevant to their job roles, and learn new skills that will benefit them both in their current positions and in future career opportunities.

This feature would not only enhance the skills of the employees, but it would also benefit the company as a whole. By investing in the development of their employees, the company is likely to see improved productivity, increased motivation, and better job satisfaction. Additionally, employees would feel valued and appreciated, leading to a more positive work environment.

Incorporating a "Skills Friday" feature would also demonstrate the company's commitment to continuous learning and development. This can be a key factor in attracting and retaining top talent, as employees are often drawn to companies that prioritize their growth and development.

Overall, I believe that Max's idea of implementing a "Skills Friday" feature to Allegrotest is an excellent initiative that would bring immense benefits to both the employees and the company.

**Comment by MaximilianMcC** [comment]
k
