### ISSUE TITLE
achievements update 🤓☝️

### ISSUE THREAD

**Issue by MaximilianMcC** [MilkyBruv/AllegroTest#16]
As a **dedicated** player of _AllegroTest, I_ believe that the addition of new achievements will greatly enhance the gameplay experience. I am therefore _requesting_ the addition of **🥳100🥳** new achievements to the game.

These achievements can range from simple tasks like completing a certain level within a specific time frame, to more challenging goals such as defeating a particularly difficult boss without taking any damage. The **addition** of these new achievements will not only give players a sense of _accomplishment_ but also provide them with new challenges to **overcome.**
![im](https://imgur.com/15zmYxE.png)
I understand that creating these new achievements may take _some time_ and effort, but I strongly believe that it will be worth it in the end. I hope that you will take my request into consideration and work towards implementing these new a_chievements_ in the near future.
# achiebemetn unclocked!!! 🥳🥳🥳🥂
Thank you for your attention to this matter.

**Comment by alexoltl** [comment]
This issue has been removed due to rule #3. 🥱 

 - Self-promotion.

**Comment by alexoltl** [comment]
This issue has been removed due to rule #15. 🥱 

 - incorrect title syntax.

**Comment by alexoltl** [comment]
reopen

**Comment by MaximilianMcC** [comment]
> 

yes

**Comment by alexoltl** [comment]
@MilkyBruv
