### ISSUE TITLE
Is there any chance of making a android port? ☝️🤓

### ISSUE THREAD

**Issue by MaximilianMcC** [MilkyBruv/AllegroTest#4]
# androuid support please
In light of the recent development of the AllegroTest project by milkybruv, it has come to our attention that there is a _pressing_ demand for an Android port of the project. Given the **ubiquity** of Android devices in the contemporary **technological landscape,** this would be a **significant step forward** in the propagation of the project's functionality and accessibility. As such, we are urgently appealing for the provision of an Android port, replete with all of the _requisite_ intricacies and complexities to ensure seamless interoperability with the Android platform. This would enable the project to penetrate a much _broader market_, with all the attendant benefits that would accrue therefrom. Therefore, we implore the **developer** to undertake this task with the utmost diligence and **expediency.**
![android support](https://i.imgur.com/iHAU2cC.png)
Many thanks 🤗🤗🤗

**Comment by alexoltl** [comment]
Please add a tag to this issue, it can greatly help the developers.
